# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import permit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businesspermit_number', models.CharField(max_length=8)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='name of the responsible organization', max_length=254, null=True)),
                ('business_email', models.EmailField(blank=True, help_text='business phone no', max_length=254, null=True, verbose_name='Business Email')),
                ('business_phone_no', models.CharField(blank=True, help_text='business phone no', max_length=255, null=True, verbose_name='Business Phone No')),
                ('business_address', models.CharField(blank=True, help_text='business physical address', max_length=10, null=True, verbose_name='Business Address')),
                ('business_profile', models.TextField(blank=True, help_text='introduce your business', null=True, verbose_name='Business Profile')),
                ('business_form', models.CharField(blank=True, choices=[(b'Sole Proprietorship', b'Sole Proprietorship'), (b'Patnership', b'Patnership'), (b'Corporation', b'Corporation')], help_text='business form', max_length=25, null=True, verbose_name='Business Form')),
                ('business_type', models.CharField(blank=True, choices=[(b'Retail Shops', b'Retail Shops'), (b'Alcohol Sales', b'Alcohol Sales'), (b'Cybers', b'Cybers')], help_text='business type', max_length=256, null=True, verbose_name='Business Type')),
                ('business_no_employees', models.CharField(blank=True, choices=[(b'Less than 5', b'5'), (b'Less than 10', b'10'), (b'Less than 20', b'20')], help_text='business no of employees', max_length=255, null=True, verbose_name='Business No. Employees')),
                ('business_class', models.CharField(blank=True, choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C')], help_text='business class', max_length=255, null=True, verbose_name='Business Class')),
                ('business_category', models.CharField(blank=True, choices=[(b'Commmercial', b'Commmercial'), (b'NGO', b'NGO'), (b'Non Profit', b'Non Profit')], help_text='business category', max_length=255, null=True, verbose_name='Businenss Category')),
                ('business_scope', models.CharField(blank=True, choices=[(b'Single', b'Single'), (b'Chain_Stores', b'Chain_Stores'), (b'Franchise', b'Franchise')], help_text='business scope', max_length=255, null=True, verbose_name='Business Scope')),
                ('business_town', models.CharField(blank=True, choices=[(b'Bungoma', b'Bungoma'), (b'Webuye', b'Webuye'), (b'Malakisi', b'Malakisi')], help_text='physical town location', max_length=255, null=True, verbose_name='Business Town')),
                ('business_street', models.CharField(blank=True, choices=[(b'Street1', b'Street1'), (b'Street2', b'Street2')], help_text='physical town location street', max_length=255, null=True, verbose_name='Business Street')),
                ('business_building', models.CharField(blank=True, help_text='building where business located', max_length=255, null=True, verbose_name='Business Buildings')),
                ('business_zone', models.CharField(blank=True, choices=[(b'CBD', b'CBD'), (b'Industrial', b'Industrial'), (b'Residential', b'Residential')], help_text='business zone', max_length=255, null=True, verbose_name='Business Zone')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('business_compliance', models.BooleanField(default=False, max_length=10, verbose_name='Business Compliance')),
                ('customer_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('business_name', 'business_zone', 'business_address', 'business_town'),
                'verbose_name_plural': 'Business Profiles',
            },
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(blank=True, choices=[(b'Owner', b'Owner'), (b'Employee', b'Employee'), (b'Agent', b'Agent')], help_text='Type of customer representing organization', max_length=54, null=True, verbose_name='Customer Type')),
                ('first_name', models.CharField(blank=True, help_text='first name', max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='last name', max_length=255, null=True, verbose_name='Last Name')),
                ('id_no', models.CharField(blank=True, help_text='ID No', max_length=255, null=True, verbose_name='ID No')),
                ('phone_no', models.CharField(blank=True, help_text='telephone number by which individuals can speak to the responsible organization or individual', max_length=255, null=True, verbose_name='Phone no:')),
                ('email', models.EmailField(blank=True, help_text='physical and email address at which the organization or individual may be contacted', max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, help_text='ZIP or other postal code', max_length=255, null=True, verbose_name='Postal Code')),
                ('picture', models.ImageField(blank=True, upload_to=permit.models.upload_folder)),
                ('town', models.CharField(blank=True, choices=[(b'Bungoma', b'Bungoma'), (b'Webuye', b'Webuye'), (b'Malakisi', b'Malakisi')], help_text='city of the location', max_length=255, null=True, verbose_name='town')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(blank=True, choices=[(b'Mpesa', b'Mpesa'), (b'Banks', ((b'KCB', b'KCB'), (b'Equity', b'Equity'), (b'StandardChartered', b'StandardChartered')))], help_text='payment mode', max_length=255, null=True, verbose_name='Payment Mode')),
                ('payment_code', models.CharField(blank=True, help_text='payment code', max_length=255, null=True, verbose_name='Payment Code')),
                ('payment_period', models.CharField(choices=[(b'Yearly', b'Yearly'), (b'Bi_annual', b'Bi_annual'), (b'Quarterly', b'Quarterly')], max_length=10)),
                ('registration_date', models.DateField(auto_now=True, help_text='registration date', null=True, verbose_name='Registration Date')),
                ('business_name', models.CharField(blank=True, help_text='name of the responsible organization', max_length=255, null=True, verbose_name='Business Name')),
                ('business_rate', models.FloatField(blank=True, help_text='business rates', null=True, verbose_name='Business Rates')),
                ('business_permit_cost', models.FloatField(blank=True, help_text='permit cost', null=True, verbose_name='Business Permit Cost')),
                ('business_last_payment', models.DateField(blank=True, help_text='last payment date', max_length=255, null=True, verbose_name='Last Payment')),
                ('business_next_payment', models.DateField(blank=True, help_text='next payment date', max_length=255, null=True, verbose_name='Next Payment')),
                ('business_inspection_date', models.DateField(blank=True, help_text='Inspection Date', max_length=255, null=True, verbose_name='Inspection Date')),
                ('customer_detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('business_name',),
                'verbose_name_plural': 'Customer Payments Account',
            },
        ),
    ]
