# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 23:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blockid', models.IntegerField(blank=True, null=True)),
                ('areacode', models.IntegerField(blank=True, null=True)),
                ('blockname', models.CharField(blank=True, max_length=50, null=True)),
                ('parcel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('sectcode', models.IntegerField(blank=True, null=True)),
                ('approval_datetime', models.DateTimeField(blank=True, null=True)),
                ('historic_datetime', models.DateTimeField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, default=b'null', max_length=15, null=True)),
                ('area', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=21037)),
            ],
            options={
                'verbose_name_plural': 'Land Parcels',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddField(
            model_name='customer_payment',
            name='permits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permit.Business_permit'),
        ),
        migrations.AddField(
            model_name='business_profile',
            name='parcel_no',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='permit.Parcels'),
        ),
    ]
