# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_auto_20160108_0218'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='business_profile',
            managers=[
            ],
        ),
    ]
