# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_auto_20160108_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_profile',
            name='business_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_address',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_building',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Buildings'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_category',
            field=models.CharField(blank=True, choices=[(b'Commmercial', b'Commmercial'), (b'NGO', b'NGO'), (b'Non Profit', b'Non Profit')], max_length=255, null=True, verbose_name='Businenss Category'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_class',
            field=models.CharField(blank=True, choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C')], max_length=255, null=True, verbose_name='Business Class'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Business Email'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_form',
            field=models.CharField(blank=True, choices=[(b'Sole Proprietorship', b'Sole Proprietorship'), (b'Patnership', b'Patnership'), (b'Corporation', b'Corporation')], max_length=25, null=True, verbose_name='Business Form'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_no_employees',
            field=models.CharField(blank=True, choices=[(b'Less than 5', b'5'), (b'Less than 10', b'10'), (b'Less than 20', b'20')], max_length=255, null=True, verbose_name='Business No. Employees'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_phone_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Phone No'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_profile',
            field=models.TextField(blank=True, null=True, verbose_name='Business Profile'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_scope',
            field=models.CharField(blank=True, choices=[(b'Single', b'Single'), (b'Chain_Stores', b'Chain_Stores'), (b'Franchise', b'Franchise')], max_length=255, null=True, verbose_name='Business Scope'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_street',
            field=models.CharField(blank=True, choices=[(b'Street1', b'Street1'), (b'Street2', b'Street2'), (b'Street3', b'Street3')], max_length=255, null=True, verbose_name='Business Street'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_town',
            field=models.CharField(blank=True, choices=[(b'Bungoma', b'Bungoma'), (b'Webuye', b'Webuye'), (b'Malakisi', b'Malakisi')], max_length=255, null=True, verbose_name='Business Town'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_type',
            field=models.CharField(blank=True, choices=[(b'Retail Shops', b'Retail Shops'), (b'Alcohol Sales', b'Alcohol Sales'), (b'Cybers', b'Cybers')], max_length=256, null=True, verbose_name='Business Type'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='business_zone',
            field=models.CharField(blank=True, choices=[(b'CBD', b'CBD'), (b'Industrial', b'Industrial'), (b'Residential', b'Residential')], max_length=255, null=True, verbose_name='Business Zone'),
        ),
        migrations.AlterField(
            model_name='business_profile',
            name='parcel_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='customer_type',
            field=models.CharField(blank=True, choices=[(b'Owner', b'Owner'), (b'Employee', b'Employee'), (b'Agent', b'Agent')], max_length=54, null=True, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='id_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID No'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone no:'),
        ),
        migrations.AlterField(
            model_name='customer_detail',
            name='town',
            field=models.CharField(blank=True, choices=[(b'Bungoma', b'Bungoma'), (b'Webuye', b'Webuye'), (b'Malakisi', b'Malakisi')], max_length=255, null=True, verbose_name='town'),
        ),
    ]
