# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_auto_20160108_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_profile',
            old_name='customer_detail',
            new_name='user',
        ),
    ]
