# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0005_auto_20160108_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_permit',
            name='business_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permit.Business_profile'),
        ),
        migrations.AddField(
            model_name='business_permit',
            name='dateapplied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
