# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0006_auto_20160108_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=25)),
                ('count', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kenya_field', models.FloatField()),
                ('kenya_id', models.FloatField()),
                ('number', models.IntegerField()),
                ('province_b', models.CharField(max_length=12)),
                ('class1', models.IntegerField()),
                ('district_b', models.CharField(max_length=12)),
                ('class2', models.IntegerField()),
                ('division_b', models.CharField(max_length=22)),
                ('class3', models.IntegerField()),
                ('location_b', models.CharField(max_length=24)),
                ('class4', models.IntegerField()),
                ('subloc_b', models.CharField(max_length=22)),
                ('males', models.IntegerField()),
                ('females', models.IntegerField()),
                ('total', models.IntegerField()),
                ('househds', models.IntegerField()),
                ('pop_km2', models.FloatField()),
                ('hh_km2', models.FloatField()),
                ('av_hhs', models.FloatField()),
                ('arekm2', models.FloatField()),
                ('dis', models.IntegerField()),
                ('areakmsq', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='approval_datetime',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='area',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='areacode',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='blockname',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='historic_datetime',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='length',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='parent',
        ),
        migrations.AlterField(
            model_name='parcels',
            name='blockid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='sectcode',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
