# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import permit.models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0009_auto_20160109_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_type',
            field=models.CharField(blank=True, choices=[(b'Owner', b'Owner'), (b'Employee', b'Employee'), (b'Agent', b'Agent')], max_length=54, null=True, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID No'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone no:'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=permit.models.upload_folder),
        ),
    ]
