# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0010_auto_20160109_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_permit',
            old_name='owner',
            new_name='user',
        ),
    ]
