# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0011_auto_20160110_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_permit',
            name='businesspermit_number',
        ),
    ]
