# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0012_remove_business_permit_businesspermit_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_permit',
            old_name='business_no',
            new_name='business_name',
        ),
    ]
