# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0013_auto_20160110_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_permit',
            old_name='business_name',
            new_name='business_profile',
        ),
    ]
