# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0014_auto_20160110_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_payment',
            old_name='customer_detail',
            new_name='user',
        ),
    ]
